### ISSUE TITLE
"Segmentation fault (core dumped)" When running test.py

### ISSUE THREAD

**Issue by Anikacyp** [src-d/kmcuda#42]
When I run test.py, I encounter this "Segmentation fault (core dumped)".
I use python 3.6.5 and Cuda 9.0.
Here is the build logs attachment:
[kmcuda.log](https://github.com/src-d/kmcuda/files/2089568/kmcuda.log)

does anyone have the same issue?

**Comment by vmarkovtsev** [comment]
Hi @Anikacyp 

These two lines are suspicious:

```
-- Found PythonInterp: /home/yapch/.virtualenvs/tensorflowgpu1.7_p3.6/bin/python3 (found suitable version "3.6.5", minimum required is "3") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found suitable version "3.5.2", minimum required is "3") 
```

You must be building in a virtualenv and it leaks the native environment: part of the lib is built for 3.5 and part for 3.6. Building kmcuda in Python virtualenvs such as this is officially not supported - I generally recommend never using them and stick with Docker setups.

**Comment by vmarkovtsev** [comment]
There were also some minor incompatibilities with CUDA 9, fixed in https://github.com/src-d/kmcuda/pull/43

**Comment by Anikacyp** [comment]
@vmarkovtsev thanks for the quick reply, I'll try it.

**Comment by Anikacyp** [comment]
I rebuilt with the latest repo without virtualenv used, still have the issue.
The command is: cmake -DCMAKE_BUILD_TYPE=Release -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda -D DISABLE_R=y . && make

Here's the log:
[kmcuda.log](https://github.com/src-d/kmcuda/files/2092353/kmcuda.log)

**Comment by vmarkovtsev** [comment]
The log shows that cnake used the cached options. Try `git clean -xfd` and building again. If it still crashes, build in debug mode `-DCMAKE_BUILD_TYPE=Debug` and run under gdb `gdb --args python3 ...`. At the point it crashes, exec `bt` and attach the output. Also please activate the most verbose log level in kmcuda `verbosity=2`.

**Comment by vmarkovtsev** [comment]
@hyh900220 `Illegal instruction` means that your CPU arch is older/not compatible with the arch for which the package was built. You have to build it yourself.

**Comment by vmarkovtsev** [comment]
Actually, there was no response for the original issue since 2 months, so closing. Feel free to reopen if there is new information!

**Comment by hyh900220** [comment]
my CPU is E5-1650,  motherboard is intel C602 chipset, 32G ddr3 ram.
what build command should I use?
I was use
```
 cmake -DCMAKE_BUILD_TYPE=Release -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 .
 && make
```
but it still can't run test.py, it shows ".Segmentation fault (core dumped)"

**Comment by vmarkovtsev** [comment]
Let's continue in a new issue - it is different from the screwed Python environment - the origin of this one. I think I know what is the problem in your case, it is trivial and easy to fix.

**Comment by hyh900220** [comment]
new issue to #52

**Comment by TangeniThePyGuru** [comment]
I had the same issue. the solution was to uninstall python3 and reinstall again.

it all worked fine
